### ISSUE TITLE
Files are empty after downloading

### ISSUE THREAD

**Issue by anraf1001** [chrishamm/DuetWebControl#100]
When I want to download a file from my Duet eg. "config.g". The downloaded one has only "null" inside it. The same happens when downloading several files in zip. I use DWC 2.0.0-RC2

**Comment by chrishamm** [comment]
I cannot reproduce this. What browser are you using?

**Comment by anraf1001** [comment]
Chrome

**Comment by chrishamm** [comment]
Fixed in RC3.
