### ISSUE TITLE
Pin Fan Speed is missing in 2.0

### ISSUE THREAD

**Issue by toskium** [chrishamm/DuetWebControl#106]
The current stable DWC can pin the current fan speed to lock it somewhat. This function is currently missing in 2.0.

**Comment by chrishamm** [comment]
That's true but I don't plan to add it back until a better implementation is available in RepRapFirmware [some kind of temporary override factor for M106]. I don't think a solution like the indirect one from DWC1 is ideal, which is why I decided to drop support for it (for now).
