### ISSUE TITLE
Minor Bugs

### ISSUE THREAD

**Issue by melbuh** [chrishamm/DuetWebControl#108]
Hi!
At first: Thanx for your work!

I found some minor issues in the "Tools Frame": 
- If I change the tabs to "Extra" and back, it looses the actual temperature settings.
- If DWC is displayed on a 4k Screen with scaling, the width of the dropdown-menue is not growing with the same factor as the font size does. In my case (3840x2160 with 250% scale up (of texts etc)) it shows only the first two numbers of the temperature value. 

regards, mbuh

**Comment by chrishamm** [comment]
Please give v2.0.0-RC5 a try. DWC1 is known to have scaling problems and it is about to reach its end-of-life.
