### ISSUE TITLE
Load and unload not working if tool is not active

### ISSUE THREAD

**Issue by Patrik-svobodik** [chrishamm/DuetWebControl#109]
When I click on load filament (when it is not loaded) and the tool is not active, nothing happens, I have to activate the tool and then it works

**Comment by chrishamm** [comment]
Is this the case in DWC1? It seems to be working well in DWC2-RC.

**Comment by Patrik-svobodik** [comment]
IDK because I dont have DWC1 currently installed and I am in the middle of a print, DWC2 just does not send the T0 command before the M701

**Comment by chrishamm** [comment]
Ahh, thanks, I just spotted a bug in the unload code. I will fix that in the upcoming RC4.
The load function works well and it does send a T-code if necessary - I tested that a few minutes ago.
