### ISSUE TITLE
Control All - Turn Everything Off - A Bug

### ISSUE THREAD

**Issue by OricTosh** [chrishamm/DuetWebControl#11]
I'm using the latest web version 1.11 and firmware 1.11-ch (2016-04-08) upon my duel extruder ormerod 2 printer.
In the heater temperatures box, at the far right is a control all link, 
within in that there is  a turn off everything, which when clicked would turn off hot ends and bed and show the state as off from showing active/standby
Upon the previous version, this would turn off all items (T0,T1 and bed) 
In this version it only turns off T1 and the bed, T0 remains active

**Comment by chrishamm** [comment]
This should be resolved in the upcoming DWC 1.14 and I'll publish it as soon as I can confirm everything works as intended. Meanwhile you can grab a copy of my latest beta on the Duet3D forum and check if that fixes your problem.
