### ISSUE TITLE
Chamber target temperatures arent displayed DWC2_RC3

### ISSUE THREAD

**Issue by Stephan3** [chrishamm/DuetWebControl#110]
Hello.

I have a heated chamber in my printer. In DWC1 i get correct behavior with the dropdown menu:
![DWC1](https://i.ibb.co/LZZ5hGN/chamber-dwc1.png)

In DWC2 the arrow turns but it just empty:
![DWC2](https://i.ibb.co/k2TX3R7/chamber-dwc2.png)

Thanks for taking care.
Stephan

EDIT:
There seems to be an unfilled variable:
![DWC3](https://i.ibb.co/25FDzSw/chamber-dwc3.png)

**Comment by chrishamm** [comment]
Thanks, will be fixed in RC4.
