### ISSUE TITLE
Version 2.0.0-RC4: Failed to maintain connection to 192.168.62.113 

### ISSUE THREAD

**Issue by JohnOCFII** [chrishamm/DuetWebControl#113]
Greetings,

I'm testing 2.0.0-RC4.  Testing with RepRapFirmware for Duet 2 WiFi/Ethernet 2.02(RTOS) (2018-12-24b1)

I've been switching between my Mac using either Safari or Chrome, and my iPad with Safari

On all 3 browsers, I'm now receiving the following message every 20 seconds or so:

`Failed to maintain connection to 192.168.62.113
Cannot set property 'firstLayerHeight' of undefined`

This is with a vase-mode print with 3 bottom layers sliced in Slic3r PE.  I did not start to see the messages until the 3 bottom layers were complete, and the printer started on the "vase mode" part of the print.

**Comment by chrishamm** [comment]
Thanks for your report, I'm on it. I will release RC5 tomorrow which will fix this.
