### ISSUE TITLE
[FEATURE_REQUEST] keep last job duration

### ISSUE THREAD

**Issue by Stephan3** [chrishamm/DuetWebControl#117]
Dear @chrishamm 

When a print ends. The status page(in my case) jums to all N/A. Do you see a chance to provide here the lastvalue at least for jobduration? So one can see the final jobduration?

Thanks
Stephan

**Comment by chrishamm** [comment]
Yes, I'll have a look at it. The layers are already saved when a print finishes so the print duration should be persistent too.

**Comment by Stephan3** [comment]
cool thanks. 
The warmuptime is allways N/A btw. if your are passing by the code, maybe you take a look at it, it will be probably arround the same corner.

DWC1 ist displaying this correctly.

**Comment by chrishamm** [comment]
Implemented in RC6.
