### ISSUE TITLE
2.0.0 RC6 Unable to create new macro directories 

### ISSUE THREAD

**Issue by johnkray** [chrishamm/DuetWebControl#119]
I get an error message every time I try to create a new macro directory. It says failed to create directory. You may already be aware of this, but if not I wanted to bring it to your attention.

**Comment by JohnOCFII** [comment]
I was able to successfully create a subdirectory in my Macros directory.  It was labeled "Lights."

**Comment by chrishamm** [comment]
I haven't had any problems with it either. What error message do you get?

**Comment by johnkray** [comment]
Well, it is working now. Not sure what was going on. It was happening on a couple of my printers but seems to be all good now.
