### ISSUE TITLE
2.0.0 RC6 looking good!

### ISSUE THREAD

**Issue by JohnOCFII** [chrishamm/DuetWebControl#121]
I didn't see a thread for general comments on the Release Candidates.  

I've been running RC6 now for a few days on Macintosh with both Safari and Chrome.  I've also tried on my iPad and iPhone with Mobile Safari.  It's all looking very good.

**Comment by chrishamm** [comment]
Thanks, that's nice to hear! See https://forum.duet3d.com/topic/9454/duet-web-control-2-0-0-rc6
