### ISSUE TITLE
2.0.0 RC6 - Broken temperature graph when DWC is left open overnight

### ISSUE THREAD

**Issue by Fulg** [chrishamm/DuetWebControl#124]
Leaving DWC up overnight makes the temperature display look quite interesting... :) It seems to show the entire timeline from the first time I connected to DWC _until the current time_.

![image](https://user-images.githubusercontent.com/3320405/54315269-057cb700-45b4-11e9-899e-a9b4098d3bca.png)

My PC usually sleeps during the night (so the connection with the Duet is lost for a while, even though this does not trigger a disconnection message), I don't know if it's related. I can try later disabling overnight sleep.

**Comment by Patrik-svobodik** [comment]
I left it while we were on vacation, it looks much more interesting, will
screenshot it

st 13. 3. 2019 v 22:24 odesílatel Benoit Miller <notifications@github.com>
napsal:

**Comment by chrishamm** [comment]
Will be fixed in the next version.

**Comment by chrishamm** [comment]
Fixed in RC7.
