### ISSUE TITLE
manual Extrusion from dahsboard

### ISSUE THREAD

**Issue by Stephan3** [chrishamm/DuetWebControl#125]
Hello @chrishamm 

Obviously i provide a value from klipper the wrong way. What does dwc2 ecxpect the make theese controls available? In my case they are greyed out all the time.

Thanks 
Stephan

**Comment by chrishamm** [comment]
1. A tool must be selected
2. The selected tool must have at least one extruder drive assigned
3. The tool's heater temperature must be greater than or equal to the minimum extrude/retract temperature
