### ISSUE TITLE
2.0.0 RC6 - Can't view mesh bed graph

### ISSUE THREAD

**Issue by ka15574** [chrishamm/DuetWebControl#126]
After mesh bed leveling (or at any other time for that matter) there is no way to manually view the mesh bed height map, that feature is no longer under the calibration tab on the main control page (in these release, I would suggest it be placed under Machine Control -> Dashboard -> Compensation & Calibration).

**Comment by chrishamm** [comment]
Go to "Heightmap" then, I moved it there.
