### ISSUE TITLE
2.0.0 RC6 - Unable to upload macros unless they end in .g

### ISSUE THREAD

**Issue by JohnOCFII** [chrishamm/DuetWebControl#128]
According to https://duet3d.dozuki.com/Wiki/Setting_up_macro_files_for_common_tasks macros are not required to end in .g but the upload filter must be blocking files with different names, as they are all grey'd out, other than those ending in .g.  Tested with Safari and Chrome on a Mac.

**Comment by chrishamm** [comment]
Thanks for the note, I'll change the filter for macro files.

**Comment by chrishamm** [comment]
Fixed in RC7.
