### ISSUE TITLE
Fan name (C parameter) is not picked up by Web Control UI, when set in config.g

### ISSUE THREAD

**Issue by 3Dpassion** [chrishamm/DuetWebControl#132]
Fan name (C parameter) is not picked up by Web Control UI, when set in config.g I checked request #75 where you said it works and closed it, but it doesn't work. I just tried it and I still have Tool fan and Fan0

**Comment by 3Dpassion** [comment]
Actually I am sorry, I have to rephrase. Fan 0 is actually working, but "tool fan" isn't, no matter what you set, it would still show "tool fan"

**Comment by chrishamm** [comment]
The "Tool Fan" selection is meant to control the fan assigned to the selected tool (see M563). It is controlled when M106 without a P-parameter is sent to the firmware. Why would it make sense to allow this label to be renamed?
