### ISSUE TITLE
Grid Size Parameters not set

### ISSUE THREAD

**Issue by cdedwards** [chrishamm/DuetWebControl#136]
In my config.g I have set the grid size to 10:490 10:390 S22 using M557.
This is not populated in the DWC Define Area for Mesh Compensation. It always has a default set of 0-200 and 20/20

The effect of this is that I need to enter a grid size using the menu before I can run Mesh Compensation at all.

**Comment by chrishamm** [comment]
That dialog box is just a convenience function for first tests, e.g. to determine the range of acceptable probe points. There is no need to change the mesh size if you already specify it in config.g - just run G29 or start it via "Run mesh compensation".
