### ISSUE TITLE
2.0.0 RC6 - M291 issue

### ISSUE THREAD

**Issue by dandancheeseandham** [chrishamm/DuetWebControl#137]
The following macro code functions on DWC1, but not on DWC2. It leaves DWC2 in a "busy" state, until the whole page is manually refreshed, whereupon it will continue operation.

```
M291 R"Test" P"Message 1" S3
M291 R"Test" P"Message 2" S3
```

If pauses are inserted, it then the macro will work on DWC2 and continue operation.

```
M291 R"Test" P"Message 1" S3
G4 P500
M291 R"Test" P"Message 2" S3
G4 P500
```

**Comment by chrishamm** [comment]
Thanks for your report, I will fix it soon.

**Comment by chrishamm** [comment]
Fixed in RC7.
