### ISSUE TITLE
Stray clicks in editor may lead to a reboot and corrupt files

### ISSUE THREAD

**Issue by jbitterly** [chrishamm/DuetWebControl#139]
Twice now I've gone to click "Save" when editing my config.g in the system editor, clicking roughly in the highlighted circle here:
![click1](https://user-images.githubusercontent.com/5024568/59076882-ce265980-88c7-11e9-8ee8-4ea0e8bb7322.png)

and have accidentally double clicked instead of single clicked which leads to a click being registered here:
![click2](https://user-images.githubusercontent.com/5024568/59076915-ee561880-88c7-11e9-9f10-774e0c244751.png)

which reboots the Duet board while it is trying to write my changes and results in a corrupted config.g file and no boot.  Oops.  

I think it would be a little safer if the system editor were drawn below the title bar containing the Emergency Stop button, this way you can't accidentally click it when trying to save your file and as a bonus, the E-Stop is available even if you are making a modification to a file.

**Comment by dandancheeseandham** [comment]
Ahhh. I'd wondered what had happened about a month ago, when I managed to save my config and it broke. It showed a 0B file afterwards...

**Comment by jbitterly** [comment]
Yea, it took me a minute to figure out what I had done the first time.  Once I pulled the SD card and noticed the bad config file I was able to restore from the backup and reproduce the feat shown above.

**Comment by chrishamm** [comment]
This will be fixed in DWC 2.0.1. Thanks for your report!

**Comment by chrishamm** [comment]
Fixed in v2.0.1.
