### ISSUE TITLE
No RC7 in releases section of GitHub

### ISSUE THREAD

**Issue by ctilley83** [chrishamm/DuetWebControl#142]
I hear people running RC7 in other forums.  Is it officially released? I don't see it in the releases section.

**Comment by rafaljot** [comment]
https://github.com/chrishamm/DuetWebControl/tree/2.0.0-RC7

**Comment by JohnOCFII** [comment]
Odd that it does not show up at the top of that list -- RC-6 would appear to be the latest unless you scroll down.

**Comment by rafaljot** [comment]
<img width="410" alt="image" src="https://user-images.githubusercontent.com/13086437/59199415-2eeab600-8b96-11e9-9f8e-8604005f1e8e.png">

**Comment by ctilley83** [comment]
> https://github.com/chrishamm/DuetWebControl/tree/2.0.0-RC7

That's not it. The last commit to that repository was 7 moths ago.  The latest changes are in the "next" branch

**Comment by ctilley83** [comment]
<img width="935" alt="image" src="https://user-images.githubusercontent.com/746467/59220056-fba62800-8b91-11e9-9f1b-b5ad5aa63a62.png">

This is where it should be

**Comment by cdedwards** [comment]
maybe you could run the npm install and npm run build commands after installing npm. in other words build it yourself.
![Screenshot_6](https://user-images.githubusercontent.com/2271505/59243859-50b45f00-8bcf-11e9-8b11-21626d406449.jpg)

**Comment by chrishamm** [comment]
I think the RC7 tag pointed at the wrong branch so I just recreated it and updated the release. Should be all good now. Thanks for reporting it!
