### ISSUE TITLE
Version 2.0.0-RC7 - Revert to old ver and.. cant back to RC7

### ISSUE THREAD

**Issue by GivvHub** [chrishamm/DuetWebControl#143]
Hello, I installed v. RC07, at settings i saw options to clik to revert to old version. Clicked it to test and... its all, in old ver cant see options to back again to newest ver

**Comment by chrishamm** [comment]
Then upload the new version again and you'll be back on RC7. If that doesn't help, clean the cache of your browser once or force-reload the page by pressing Ctrl+Shift+R.
