### ISSUE TITLE
Version 2.0.0-RC7 - Cant see checkbox Show ATX Power control

### ISSUE THREAD

**Issue by GivvHub** [chrishamm/DuetWebControl#144]
Cant see checkbox Show ATX Power control, its visible by default and if i not using it - cant disable visibility at main page and in settings sections

![ScreenShot3](https://user-images.githubusercontent.com/51952341/59981063-d3d9aa00-95fe-11e9-938c-5762783c8e0e.jpg)

**Comment by chrishamm** [comment]
I decided to change RRF to flag whether ATX control (M80/M81) is used or not and to display that panel only if that is the case.

**Comment by chrishamm** [comment]
Upgrade to RRF3 and use M80/81 in your config.g to make it show up.
