### ISSUE TITLE
Tools Extra temp - switch always OFF

### ISSUE THREAD

**Issue by GivvHub** [chrishamm/DuetWebControl#145]
Tools - Extra: here We can switch ON or OFF extra temp to show in chart. But this always is OFF. I changed it many many times, in chart i see extra graph, but if go to tools, extra, switches are off

![ScreenShot2](https://user-images.githubusercontent.com/51952341/59981038-8eb57800-95fe-11e9-8d69-5c08e14949ce.jpg)

**Comment by GivvHub** [comment]
![ScreenShot2](https://user-images.githubusercontent.com/51952341/59981032-72b1d680-95fe-11e9-8a57-63ac7e18637e.jpg)

**Comment by chrishamm** [comment]
Thanks, I could reproduce this problem and will fix it in the upcoming version.

**Comment by chrishamm** [comment]
Fixed in v2.0.0.
