### ISSUE TITLE
P0 fan- "Tool Fan" name always visible even when we change the name

### ISSUE THREAD

**Issue by GivvHub** [chrishamm/DuetWebControl#146]
I changed name of P0 fan:
M106 P0 L0 X255 C"Cooling printout"
And its visible at main page, at the end, sections: fan control, but is visible default tool fan too. Shoud be one name for one fan

![ScreenShot1](https://user-images.githubusercontent.com/51952341/59981018-501fbd80-95fe-11e9-87e2-8f4f8955ec58.jpg)

**Comment by chrishamm** [comment]
Your report does not describe the tool fan correctly - the tool fan is the one that is assigned to the currently selected tool, which only defaults to fan 0 (see M563 F-parameter). I agree it would make sense to hide the corresponding selection box if no fan is selected or if the currently active tool does not have any fans assigned to it, though.

**Comment by chrishamm** [comment]
DWC2 displays the "Tool Fan" only if the currently selected tool has at least one fan assigned. Hence I'm closing this.
