### ISSUE TITLE
2.0.0 RC7 - Can't right-click file in Mac Safari

### ISSUE THREAD

**Issue by JohnOCFII** [chrishamm/DuetWebControl#149]
I just upgraded from RC6 to RC7 and realized I can't right-click files in the list to make a selection (such as to delete the file).

Rolling back to RC6 and the ability to right click, then select an action behaves as expected.

**Comment by fundix** [comment]
I have Safari too, but I can click normaly. 
<img width="347" alt="Snímek obrazovky 2019-09-01 v 11 58 38" src="https://user-images.githubusercontent.com/6098688/64074764-e122ad00-ccaf-11e9-8f77-b2e16e5dc2ca.png">

**Comment by JohnOCFII** [comment]
Hmm...  I'll have to try RC7 again.

**Comment by chrishamm** [comment]
Did that apply to Safari on OS X or on an iPad/iPhone?

**Comment by JohnOCFII** [comment]
> Did that apply to Safari on OS X or on an iPad/iPhone?

That was OS X.  I'll have to update to the released version and check again.  Also, Safari has been updated since then as well.  I'm away from my printer for a couple of days, but hope to get to this Wednesday.

**Comment by chrishamm** [comment]
I just tried it on OS X 10.14.2 and it works perfectly there. If this problem shows up again, please open a new issue with instructions on how to reproduce it.
