### ISSUE TITLE
RC7 - Tool, extruder and speed all stay increased 

### ISSUE THREAD

**Issue by tonypartridge** [chrishamm/DuetWebControl#152]
When I increase the extruder, fan or speed on a print it works great. But, when I upload a new GCODE for printing it doesn’t reset them to defaults?

I would expect it too, because you might have increased it for the final print to be say 150% but would not want to start a print at this

**Comment by tonypartridge** [comment]
Check this, just noticed it on checking my state. 

000000 speed factor

![51F4E4C8-E3F6-4F9B-B8B8-75BDA174E195](https://user-images.githubusercontent.com/1400982/61832452-18a86900-ae69-11e9-8011-1e989c41fd00.png)

**Comment by chrishamm** [comment]
Seeing 0000 in the slider tip isn't nice, I will fix that. Thanks for pointing it out.

To reset the values to your defaults I suggest you either add M0/M1 to your end G-code and edit stop.g/sleep.g accordingly or you add the corresponding instructions (M220/221) right to your end G-code.

If you are not happy with this, I suggest you open a new issue on the RepRapFirmware repository.

**Comment by tonypartridge** [comment]
Great thanks, if that’s how DUET natively handle it it’s fine. Its just a little unexpected from a users point of view.

**Comment by chrishamm** [comment]
Fixed in v2.0.0.
