### ISSUE TITLE
Feature Request - Disable Home X, Home Y, Home Z on delta printers to avoid accidental damage

### ISSUE THREAD

**Issue by SSMagic** [chrishamm/DuetWebControl#156]
On a delta printer homing a single axis could potentially damage the printer by sending one axis to the top end stop with others remaining low. To avoid such possible accidental damage it is suggested this feature should be disabled, either manually in settings or automatically if a delta printer is configured in settings.

**Comment by chrishamm** [comment]
Thanks for reporting this, the homing buttons for individual axes should be hidden on a delta printer (like on DWC1). Will be fixed soon.

**Comment by chrishamm** [comment]
Fixed in v2.0.0.
