### ISSUE TITLE
Dark Theme and System Editor font color

### ISSUE THREAD

**Issue by zeplintwo** [chrishamm/DuetWebControl#16]
When using the dark theme for the user interface there is a issue with the font color when trying to edit files from the system editor. When you use the 'edit this file' icon the window/GUI that opens the text is displayed in a light grey that is only a few shades darker than the white background. 

The file data is there. And can be edited but to see changes or review setting you have to highlight the text to see it. 

BTW, this is a great addition to the web interface.

Here are some screen captures of what I am seeing:
http://imgur.com/a/5RLG6

**Comment by chrishamm** [comment]
Thanks for the info, I'll fix it in the official 1.12 release.
