### ISSUE TITLE
Multiple bed heaters

### ISSUE THREAD

**Issue by percarsten** [chrishamm/DuetWebControl#163]
Is it possible to display more than one bed heater temperature and temperature in the graph
I have 2 bed heaters each with its own sensor connected to the duet wifi independent outputs and temperature inputs.

**Comment by chrishamm** [comment]
Yes, this will be possible with DWC2.

**Comment by chrishamm** [comment]
DWC2 has been released supporting multiple heated beds. If you are using a Duet 2 or Maestro and cannot see multiple beds, I suggest you open a new issue in the RepRapFirmware repo since it would need another change of the status response.
