### ISSUE TITLE
1368 x 768 resolution screen issues

### ISSUE THREAD

**Issue by escknx** [chrishamm/DuetWebControl#167]
Using small laptop w 1368 x 768 screen resolution.
Tools - Active temperature, only first digit is visible. Instead of 210 I see only 2 when clicking on it. Standby temperature is shown correctly.

**Comment by chrishamm** [comment]
I'll make the temperature inputs a bit wider.

To display the temperatures properly for now, you can hide the main menu by pressing on the button in the top left corner.

**Comment by chrishamm** [comment]
Fixed in v2.0.3.
