### ISSUE TITLE
DWC 2.02 reports file upload succeeded even if RRF returns failure

### ISSUE THREAD

**Issue by dc42** [chrishamm/DuetWebControl#169]
If a CRC mismatch occurs when DWC uploads a file to RRF, RRF returns {err:1} (according to WireShark). However, DWC 2.02 reports thast the upload succeeded, and if it is a firmware file, offers to install it (even though there is no file to install because it has been deleted).

**Comment by chrishamm** [comment]
Fixed in v2.0.3.
