### ISSUE TITLE
Edge browser failure

### ISSUE THREAD

**Issue by Resonanz** [chrishamm/DuetWebControl#171]
If you have a long list of macros (e.g. 20), a scroll bar appears on the right side of the list (on the "Macros" side tab). On Edge, the scroll bar does not appear, and the lower macros become unavailable as the screen annoyingly auto scrolls back to the top each time yo try to scroll to the lower down macros.

I should add that the scroll bar does appear when using Brave browser (which uses the Chrome engine).

**Comment by chrishamm** [comment]
Since I haven't got any more feedback I am closing this issue.
