### ISSUE TITLE
Ver 2.0.4 "Auto Sleep" does not work 

### ISSUE THREAD

**Issue by wtarantul** [chrishamm/DuetWebControl#175]
Updated to version 2.0.4 from version 2.0.0-RC3.
 On version 2.0.0-RC3, everything worked. What could be the problem ?

**Comment by chrishamm** [comment]
Thanks, I could reproduce this problem and will fix it in v2.0.5.

**Comment by chrishamm** [comment]
Fixed in v2.0.5.

**Comment by mmontminy** [comment]
Was there a regression with Auto Sleep? It hasn't worked for either of my printers for the last several releases. Currently running 2.1.3 on 2 printers with a Duet2 and Maestro. Neither appear to be calling sleep.g when Auto Sleep is selected during a print.

**Comment by chrishamm** [comment]
It works as expected both on my Duet 3 and on my Duet WiFi.

**Comment by mmontminy** [comment]
So is there a way to debug it then? I haven't been able to get it to work for quite some time.

**Comment by chrishamm** [comment]
What firmware are you using? Be aware that the DWC tab needs to remain open and it has to stay connected for this feature to work.

If that is the case, please open the JS console via F12 and copy the full output of

```
JSON.stringify(machineStore
```

once before the print finishes and just after it has finished. You can look at the network requests for rr_gcode requests too, you should find one in there where DWC sends M1 to RRF.

**Comment by mmontminy** [comment]
I should have realized that DWC needs to be running for this to work. I'm
willing to bet that's the case. I was thinking it was something happening
in the firmware, not the browser.
