### ISSUE TITLE
FEAT: RTSP Webcam Feed Support

### ISSUE THREAD

**Issue by ondrovic** [chrishamm/DuetWebControl#176]
Was wondering if there was a way to add support for the RTSP feed from the new Wyze firmware.

protocol is as so:

rtsp://user:pass@ip/live

currently doesn't seem to be working in version 2.0.4
![2019-11-08 17_37_14-(69 2%) Darth Bobo](https://user-images.githubusercontent.com/3682042/68517763-7a40e780-024e-11ea-8753-77a3d5ce245e.png)
![2019-11-08 17_38_55-(77 4%) Darth Bobo](https://user-images.githubusercontent.com/3682042/68517809-ac524980-024e-11ea-9fce-865284386fdc.png)

**Comment by chrishamm** [comment]
RSTP is not supported by web browsers so there is no way to add support for it.

**Comment by JohnOCFII** [comment]
@ondrovic - I use VLC in one window to view the RTSP stream, and have DWC up in another window.  Works great on my Mac and iPad.  https://www.videolan.org
