### ISSUE TITLE
Temperature chart autoscaling

### ISSUE THREAD

**Issue by Resonanz** [chrishamm/DuetWebControl#182]
Hi, the temperature chart on my screen displays 0-250 degC but my temperatures are around 30-40 degC, and thus quite difficult to read. It would be nice if the chart y-axis auto-scaled. Thanks.

**Comment by chrishamm** [comment]
Actually DWC2 already auto-resizes the Y scale depending on your configured heater protection. If you do not need to exceed 50C or so, reconfigure the maximum allowed heater temperatures using M143.

Rescaling individual heaters is not really feasible.
