### ISSUE TITLE
Refresh Joblist for Simulation Times?

### ISSUE THREAD

**Issue by DocTrucker** [chrishamm/DuetWebControl#183]
Version: 2.0.4
Duet Hardware: v0.6 + Shield
Duet Firmware: 1.24

Need to press refresh to see the simulation time. Can't this be done on the initial 'Jobs' page/tab/screen  load?

**Comment by chrishamm** [comment]
The file list should be reloaded when the simulation is complete. Thanks for pointing that out, it will be fixed in the next version.

**Comment by chrishamm** [comment]
Fixed in v2.0.5.

Also support for the Duet 0.6/0.8.5 has been added again but I haven't tested it yet - YMMV.
