### ISSUE TITLE
Tab spacing not sticking

### ISSUE THREAD

**Issue by jaysuk** [chrishamm/DuetWebControl#185]
When editing a config file in DWC 2.04, if it is desired to increase the space between the code and comments, it is typical to add "tabs" to move the text over accordingly.
If this is done by itself, when saving a file the tabbed spaces disappear.
If tabs are inserted followed by a space, the tabbed spaces stay.

**Comment by chrishamm** [comment]
Thanks for the note, I'll fix it in the next version.

**Comment by chrishamm** [comment]
Fixed in v2.0.5.
