### ISSUE TITLE
DWC not showing new data if gcode file is changed

### ISSUE THREAD

**Issue by jaysuk** [chrishamm/DuetWebControl#186]
For example, if a file is uploaded that is sliced with a layer height of 0.2 and this is uploaded to a duet, the correct file information is displayed.
If this file is then resliced with a layer height of 0.1 and uploaded as a file with the same name, the relevant information (layer height, filament usage etc) is not refreshed.

**Comment by chrishamm** [comment]
Yes, that makes sense. I'll fix it in the next version. Thanks for the report!

**Comment by chrishamm** [comment]
Fixed in v2.0.5.
