### ISSUE TITLE
Screen resizing priorities

### ISSUE THREAD

**Issue by LykleSchepers** [chrishamm/DuetWebControl#19]
Hi Christian,

This is a small issue but annoying.
When I resize the webpage, while I am in the Machine Control page, the Home All button is not visible. 
The title bar Head Movement gets priority over the Home All button. This should be the other way around.

Quite often I have the screen relatively small on my monitor as I am doing other stuff but I still want to keep an eye on it. If something goes wrong, I can Cancel but not Home All. 

Thanks
Lykle

**Comment by chrishamm** [comment]
If this problem is still present, it will be fixed in DWC 1.13.
