### ISSUE TITLE
ATX Power box

### ISSUE THREAD

**Issue by fundix** [chrishamm/DuetWebControl#190]
I updated to RepRap 3 and web control 2.0.4 and after reboot ATX Power dialog in Dashboard is missing.

I solved problem by adding M81 (switch off) command to the Config ... after Reboot I can now see ATX Power dialog.

ATX Power dialog shows when I type M80/M81 into console too.

**Comment by chrishamm** [comment]
In that case leave M80/81 in your config.g. This behaviour is expected and it will not be changed anytime soon.
