### ISSUE TITLE
Missing and incorrectly positioned responses on Console page

### ISSUE THREAD

**Issue by dc42** [chrishamm/DuetWebControl#191]
Using DWC 2.0.4. Very often, when a printer has been turned off but DWC left running in the browser, after I turn on the machine and DWC reconnects, responses from commands don't appear in the Console window. Refreshing the browser tab fixes it. Recently I had this happen, then I noticed that the responses were present but had been inserted in the wrong place. Here is the complete console log:

04/01/2020, 23:18:24 | Connection interrupted, attempting to reconnect...Network error
-- | --
04/01/2020, 18:12:29 | G32Calibrated 8 factors using 16 points, deviation before 2.030 after 0.019
04/01/2020, 18:11:25 | Connection established
04/01/2020, 18:11:11 | Connection interrupted, attempting to reconnect...
04/01/2020, 18:11:09 | Upload of Duet2CombinedFirmware.bin successful after 1s
04/01/2020, 18:10:49 | Connected to 192.168.1.125
06/01/2020, 15:08:39 | M408 P1{Electronics:{MainBoard:{MaxHeaters:10,MaxMotors:12,Name:"Duet 2 WiFi",ShortName:"2WiFi"}},Heat:{ColdExtrudeTemperature:160.0,ColdRetractTemperature:90.0},Move:{Daa:{Enabled:"no",MinimumAcceleration:10.0,Period:0.0},Idle:{Factor:0.3,Timeout:30000},PrintingAcceleration:10000.0,TravelAcceleration:10000.0,SpeedFactor:100.0},Network:{Interfaces:[{ActualIP:"192.168.1.125",FirmwareVersion:,Gateway:"0.0.0.0",Subnet:"255.255.255.0",Type:"wifi"}]}}
06/01/2020, 15:08:08 | Connection established
06/01/2020, 15:07:55 | Connection interrupted, attempting to reconnect...
06/01/2020, 15:07:53 | Upload of Duet2CombinedFirmware.bin successful after 1s
06/01/2020, 15:07:40 | Connection established

So the responses were added at the bottom instead of at the top. Perhaps this is always the case when responses appear to be missing.

**Comment by chrishamm** [comment]
This should be fixed in v2.0.5.
