### ISSUE TITLE
DWC doesn't account for use of M505 to change the sys files path

### ISSUE THREAD

**Issue by dc42** [chrishamm/DuetWebControl#193]
DWC 2.0.4 doesn't allow for the user using M505 to change the sys files path. As a result, when a user runs G29, the height map is saved in the current sys dir bur DWC always looks in /sys for it. So DWC fails to display the height map, por displays the wrong one. When retrieving a height map, DWC should look in the folder given by the "sysdir" variable, if that variable is provided.

**Comment by chrishamm** [comment]
I'll fix this in the next DWC version.

**Comment by chrishamm** [comment]
Works in v2.0.6.
