### ISSUE TITLE
DWC sometimes uploads firmware files to wrong subfolder

### ISSUE THREAD

**Issue by dc42** [chrishamm/DuetWebControl#194]
If a on the System page of DWC goes into a subfolder, any uploads done on the System page go into that subfolder. But this is not correct for firmware files and IAP files; so it can lead to users uploading a new firmware file and then wondering why it doesn't get installed. Binary files should always be uploaded to /sys.

**Comment by chrishamm** [comment]
Firmware files are always uploaded to 0:/sys but it isn't the case for IAP files. I'll change DWC2 accordingly.

**Comment by dc42** [comment]
I suggest DWC upload all .bin files to /sys, as i can't think of a reason why a .bin file would ever go anywhere else.

**Comment by chrishamm** [comment]
DWC 2.0.5 uploads IAP files of the current board to 0:/sys. Since users uploading firmware files from a sub-directory of /sys is a rather rare scenario, I think this solution will be sufficient.
