### ISSUE TITLE
Temperature selection

### ISSUE THREAD

**Issue by CrazyCreator13** [chrishamm/DuetWebControl#199]
You can no longer set the temperature manually. Always jumps back to 0 immediately.

If you start a print it works.
However, if you want to change one of the temperatures during printing, it always jumps back to the originally set temperature.

P.S.
Browser: Chrome

**Comment by chrishamm** [comment]
It generally works for me but sometimes the input control seems to select a wrong item and sends "0" instead of the entered value. I'll fix this in the next version, thanks for reporting it

**Comment by CrazyCreator13** [comment]
no problem ... you have the work, I only had to write a few lines of text.

Thank you very much for your work

**Comment by chrishamm** [comment]
This has been fixed in DWC 2.0.6.
