### ISSUE TITLE
Ajax Error -  Communication Error

### ISSUE THREAD

**Issue by joyceck** [chrishamm/DuetWebControl#20]
An AJAX error has been reported, so the current session has been terminated.
Please check if your printer is still on and try to connect again.
Error reason: Not authorized.

Others have tried to resolve this no progress. Ideas?

**Comment by chrishamm** [comment]
Which electronics and DWC+firmware versions are you using?

**Comment by chrishamm** [comment]
If you are using my 1.03 fork of DuetWiFiServer (if you use a Duet WiFi) or if you upgrade to the latest RepRapFirmware version, this should be fixed.
