### ISSUE TITLE
DWC displays wrong height map

### ISSUE THREAD

**Issue by dc42** [chrishamm/DuetWebControl#207]
If you load a specific height map using G29 S1, then if you select Height Map in DWC, users expect it to show the height map that has been loaded. But it always shows heightmap.csv instead.

Suggestion:
1. We add the current height map filename to the object model (full path from SD card root)
2. The SD version of DWC uses rr_model to query the height map name (if the firmware supports rr_model) and uses that height map file. It would also be helpful to display the name of the height map file alongside the height map.

**Comment by chrishamm** [comment]
In fact it is already part of the object model but it may be that the file is not automatically reloaded when it is modified (see [here](https://chrishamm.github.io/DuetSoftwareFramework/api/DuetAPI.Machine.Move.html#DuetAPI_Machine_Move_HeightmapFile)). Does RRF change the reported compensation type to "None" when a new height map is being probed?

**Comment by dc42** [comment]
Yes it does set it to None at the start of probing.

**Comment by chrishamm** [comment]
Will be fixed in DWC 2.1.0. Whenever `move.compensation.file` changes, the heightmap will be reloaded from the given path.
