### ISSUE TITLE
Multiple heated chambers not working correct

### ISSUE THREAD

**Issue by dvmourik** [chrishamm/DuetWebControl#208]
We have 2 different heated chambers M141 P0 H2 and M141 P1 H3 defined. When typing this manually in console they work like a charm. Using the interface temperatures will allways set Chamber number 1 and put it on active, never Chamber 2.

**Comment by chrishamm** [comment]
Please check if the problem persists with DWC 2.1.0.

**Comment by chrishamm** [comment]
Haven't got any more feedback, closing.
