### ISSUE TITLE
Configure Remote Device

### ISSUE THREAD

**Issue by ProtoThis** [chrishamm/DuetWebControl#211]
Hi,

This isn't really an issue as it being something wrong with the code but mainly a quick question how to. I am trying to do some development on this project. I have the NPM source running on my development machine but want to connect the webinterface to my actual DuetWifi board. How / where do I configure which IP to connect to (the old html5 + js DWCv1 interface showed a connect to dialog)?

Kind regards,

Ferry

PS
When looking at the traffic generated by the site it tries to connect to my localhost (on port 8080) and the ip of my development machine.

**Comment by chrishamm** [comment]
I generally run `npm run serve`, connect to localhost:8080 and then a connect prompt is shown just like in DWC1. However it is important to either use `localhost` or `127.0.0.1` (or its IPv6 equivalent) so DWC understands it is operating from localhost. If you connect to your local dev server using the machine name, the connect button will not be shown.
