### ISSUE TITLE
DWC 2.07 mobile extra temperature view not same as for tools

### ISSUE THREAD

**Issue by pipersw** [chrishamm/DuetWebControl#213]
In mobile view the view is not the same for tools temperature and extra temperature.
Could be the same view for extra as for tools view ?
![Screenshot_2020-02-06-00-34-54-957_com android chrome](https://user-images.githubusercontent.com/3940435/73893219-4d19ca80-4879-11ea-8f65-c8065baf1036.jpg)
![Screenshot_2020-02-06-00-34-40-584_com android chrome](https://user-images.githubusercontent.com/3940435/73893224-53a84200-4879-11ea-867c-ac0659781676.jpg)

**Comment by chrishamm** [comment]
Yes, absolutely, I'll fix it in DWC 2.1.0. Thanks for reporting this!
