### ISSUE TITLE
Warning from npm...

### ISSUE THREAD

**Issue by bjbeare** [chrishamm/DuetWebControl#217]
I'm building from source and noticed the following warning. Is this a concern?
Ty!

pi@duet3:~/DuetWebControl $ npm install
npm WARN npm npm does not support Node.js v10.15.2
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/

**Comment by chrishamm** [comment]
It sounds like your npm versions are not up-to-date. I suggest you update the packages once via `sudo apt-get update` and `sudo apt-get upgrade`. Then check if the warning persists.

In any case, I usually develop DWC on a separate machine so I cannot really comment on this issue.
