### ISSUE TITLE
Stuck in connecting...

### ISSUE THREAD

**Issue by bjbeare** [chrishamm/DuetWebControl#218]
pi@duet3:~/DuetWebControl $ npm install
npm WARN npm npm does not support Node.js v10.15.2
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/

I then connected to:
http://10.0.0.50:8080. The interface came up but is stuck at "connecting...".
Screenshot enclosed.

![Screenshot from 2020-02-21 09-32-31](https://user-images.githubusercontent.com/1189877/75057187-50be6b80-548d-11ea-978a-cd208fecf87a.png)

**Comment by bjbeare** [comment]
I further tried...
   30  npm run build
   56  unzip -d TEST dist/DuetWebControl-SBC.zip 
   57  ln -s $(pwd)/TEST /opt/dsf/dwc2/TEST

Then connected (externally) to http://10.0.0.50:TEST/index.html
The browser showed a blank page.
Screenshot attached.

... I'm more of a C developer... once I get a starting point on how to deploy/test this, I'll catch up on .js pretty quickly.
Thanks!
![Screenshot from 2020-02-21 10-04-15](https://user-images.githubusercontent.com/1189877/75059367-ad238a00-5491-11ea-82a5-3eeb64e007ea.png)

**Comment by chrishamm** [comment]
I've been able to reproduce this a couple of times and it will be fixed in DWC 2.1.0.
