### ISSUE TITLE
download temperature data from graph as .csv file

### ISSUE THREAD

**Issue by bjbeare** [chrishamm/DuetWebControl#219]
If there is a heater failure, it may be some time before the operator gets back to the printer and finds the error. The temperature graph is great for seeing what happened... but unfortunately the needed data may have rolled off of the graph or there may have been a transient that isn't really very visible.

I propose an enhancement to download a .csv file with the temperature data history for of-line analysis.

Note... I plan to work on this feature and will submit back. Please let me know if you approve of the concept.

**Comment by chrishamm** [comment]
I'll be happy to accept a pull request for this feature but I won't implement it myself :) If you see spiks etc it is usually sufficient to share a screenshot for support requests.
