### ISSUE TITLE
"Start Again" after Cancelling a Simulation Starts a Print

### ISSUE THREAD

**Issue by DocTrucker** [chrishamm/DuetWebControl#221]
All in the title really! Before I start a simulation that is going to take a few minutes I like to set the bed to warm up first. I forgot, cancelled the simulation, started the bed and attempted a restart. This started a live build process instead of a simulation.

DWC: 2.0.7
RRF: 1.26.1
Hardware: First Generation v0.6

**Comment by chrishamm** [comment]
Thanks for reporting this, will be fixed in DWC 2.1.0.
