### ISSUE TITLE
Certain .bin files not renamed on upload

### ISSUE THREAD

**Issue by jaysuk** [chrishamm/DuetWebControl#222]
When uploading Duet3Firmware_EXP3HC.bin, if it includes, for example, "(1)" because multiple versions of the file have been downloaded, the "(1)" is not removed and the original file is not overwritten.

If Duet3Firmware_MB6HC.bin is uploaded with "(1)" in the name (like this Duet3Firmware_MB6HC (1).bin) the file is renamed and overwrites the original file.

This error also occurs for Duet3_SDiap_MB6HC.bin

**Comment by chrishamm** [comment]
This will be fixed in DWC 2.1.0 but it will require CAN board enumeration, which is still to be done in RRF AFAIK.
