### ISSUE TITLE
DWC 2.1.1 "Cannot read property 'reply' of null"

### ISSUE THREAD

**Issue by anraf1001** [chrishamm/DuetWebControl#225]
After updating DWC to version 2.1.1 I can't access my printer's web interface. It only says: 
`Connection interrupted, attempting to reconnect... Cannot read property 'reply' of null`
It looks like it gets into some kind of loop.

**Comment by chrishamm** [comment]
You are probably using RRF 3.01-RC5 or older so this error message comes up. Open up the JavaScript console, enter `forceLegacyConnect = true` and upgrade your firmware.

**Comment by anraf1001** [comment]
Thanks. Now it works :D
