### ISSUE TITLE
Wrong number of fans and speed

### ISSUE THREAD

**Issue by CrazyCreator13** [chrishamm/DuetWebControl#231]
From version 2.0.8 to today's 2.1.3 i get 8 fans in the overview.
If I look at Status I only get 2 displayed. Hot end fans and tool fans ... But both show 0 speed even though they run 100%.

If I install version 2.0.7 everything is ok

Electronics
Board: Duet WiFi 1.04
RepRapFirmware for Duet 2 / Version:  2.05.1 (2020-02-09b1)
Duet WiFi Server version: 1.23

**Comment by chrishamm** [comment]
RRF 2 won't be supported much longer so please consider upgrading to RRF 3.

**Comment by CrazyCreator13** [comment]
Oh ... I didn't know that. Then I will deal with adjusting the config files.

**Comment by chrishamm** [comment]
Fixed in DWC 2.1.4.

**Comment by CrazyCreator13** [comment]
cool ... thanks
