### ISSUE TITLE
Define Area for Mesh Compensation still not working?

### ISSUE THREAD

**Issue by RayEbb** [chrishamm/DuetWebControl#232]
Hello,

I have a Duet2 wifi mainboard for a few weeks now.
But from DWC 2.1.0 and up, I can't define the Area for mesh compensation anymore.
When I enter the values and reopen it, then all the settings are zero again.

So now I have to change them in the config.g file, restart my board again, then set the temperatures again, before I can do a G29 command again.

**Comment by chrishamm** [comment]
Hello, the values in the "Define area for mesh compensation" dialog are only populated if you are running RepRapFirmware 3.01-RC7 or newer. If the values are different in there from what you configured, that only means that they could not be obtained from the Duet.

Consider upgrading if you are still using RepRapFirmware 2.

**Comment by RayEbb** [comment]
> Hello, the values in the "Define area for mesh compensation" dialog are only populated if you are running RepRapFirmware 3.01-RC7 or newer. If the values are different in there from what you configured, that only means that they could not be obtained from the Duet.
> 
> Consider upgrading if you are still using RepRapFirmware 2.

Thanks, for the answer. I'm using RRF 3.0 at the moment

**Comment by chrishamm** [comment]
Closing because this bug is not present when RRF 3.01 is installed.
