### ISSUE TITLE
DWC 2.1.3 Jobs page stuck spinning after multiple file upload

### ISSUE THREAD

**Issue by dc42** [chrishamm/DuetWebControl#234]
If I press Upload GCode Files on the Jobs page, select 14 small files and then press Open, the files are uploaded but the Jobs page is stuck showing the spinning "busy" indicator where the Refresh button should be, with the progress bar part way across and all files showing "loading". Even so, I can still click on a file and select an action. This happens both in standalone mode and via a RPi attached to Duet 3. Refreshing the browser tab brings it back to normal.

**Comment by chrishamm** [comment]
Thanks, I could reproduce this problem and it will be fixed in the next DWC version.

**Comment by chrishamm** [comment]
Fixed in DWC 2.1.4.
