### ISSUE TITLE
Disable zoom on mobile devices

### ISSUE THREAD

**Issue by natthapolvanasrivilai** [chrishamm/DuetWebControl#235]
The zoom functionality should be permanently disabled on all devices.
On mobile, when double tapping the XYZ jog button, the page zoom itself in, render itself unusable.

The viewport metadata should be updated to include the "user-scalable=0" attribute.

`<meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=0">`

**Comment by chrishamm** [comment]
Thanks, I'll add that to the next DWC version.

**Comment by natthapolvanasrivilai** [comment]
Thanks for resolving this in 2.1.4
