### ISSUE TITLE
PhpStorm told me that ...

### ISSUE THREAD

**Issue by Nibbels** [chrishamm/DuetWebControl#236]
Hello,

first: I am still a beginner when it comes to Vue.
I checked out the project to be able to change The UI on my printer. (I probably need that to debug some stupid behaviour when changing tools on a Toolchanger)

Well, I looked over the code and began to understand the component structure. The code seems to be really clean, except some details the linter told me.
Some of them I wanted to show those to you, in case you dont know about them because you have another development software or another linter.  So please ignore my issue here if that all is bogus.

![image](https://user-images.githubusercontent.com/3265671/79674499-169aed00-81e4-11ea-9e06-8c969952935e.png)
That seems to fix it but is it right?:
![image](https://user-images.githubusercontent.com/3265671/79674505-25819f80-81e4-11ea-84c8-49d58f3df94f.png)

I dont really understand this yet:
![image](https://user-images.githubusercontent.com/3265671/79674604-0a635f80-81e5-11ea-857c-89ed3fae53ca.png)

![image](https://user-images.githubusercontent.com/3265671/79676072-e6544e00-81e5-11ea-8738-04d07e8897d6.png)

![image](https://user-images.githubusercontent.com/3265671/79676386-08e66700-81e6-11ea-9a82-9e7c76e7c332.png)

![image](https://user-images.githubusercontent.com/3265671/79676404-2a475300-81e6-11ea-8f25-02070df2956e.png)

Greetings

**Comment by chrishamm** [comment]
Thanks for the messages. While several messages do not make sense (like `Condition is always false`) because the referenced fields are either state or getter _properties_, I'll fix the others in the next version.

**Comment by chrishamm** [comment]
Fixed in DWC 2.1.4.
