### ISSUE TITLE
Hello Christian Hammacher error in translation Spanish language

### ISSUE THREAD

**Issue by Keyn11** [chrishamm/DuetWebControl#237]
Hello Christian Hammacher error in translation Spanish language of Web control
put "Stado" and should "Estado" I am Spanish
On file es.js

**Comment by chrishamm** [comment]
Hello Heyn11, can you either upload a fixed es.js file or tell me where to correct it?

**Comment by Keyn11** [comment]
If you have it here
[es.zip](https://github.com/chrishamm/DuetWebControl/files/4506369/es.zip)
Thanks

**Comment by Keyn11** [comment]
[esFinal.zip](https://github.com/chrishamm/DuetWebControl/files/4506402/esFinal.zip)
More Changes in language
Heater Calefactor
Stado Estado
Thema Tema

**Comment by chrishamm** [comment]
I'm afraid that is no plain .js file, it is some kind of saved GitHub page that I cannot use.

**Comment by Keyn11** [comment]
I can`t send in Github Window the js files, only ZIP and check for me and download is right if you tell you email and send the file.

**Comment by chrishamm** [comment]
Please send it to christian@duet3d.com

**Comment by Keyn11** [comment]
Thanks

**Comment by chrishamm** [comment]
As much as I'd appreciate an updated translation file, I cannot merge it unless I get the **actual** JavaScript file and not an HTML file. Please send the raw file over or upload it somewhere, else I will close this issue again.

**Comment by chrishamm** [comment]
I'm closing this because the file is unusable. Feel free to send me a pull request and I'll merge your updated translations into the next version.
