### ISSUE TITLE
Multiple bed heaters

### ISSUE THREAD

**Issue by xyyzyyx** [chrishamm/DuetWebControl#240]
Is DWC able or will be able to show and control mutiple bed heaters in it's layout? That would be helpfull for machines with separate heat zones and multiple heatbeds for multiple material (different temp for different heatzones).

**Comment by chrishamm** [comment]
Yes, see [M140](https://duet3d.dozuki.com/Wiki/Gcode#Section_M140_Set_Bed_Temperature_Fast_or_Configure_Bed_Heater). Please use the [forum](https://forum.duet3d.com) for further support questions.

**Comment by xyyzyyx** [comment]
Sorry but you didn't understand me. I know M140 works, I can controll bed heaters via gcode but I cannot see all bed heaters in DWC layout. There is only one bed heater that I can see, 
![heaters](https://user-images.githubusercontent.com/38016403/80482067-d78f3900-8953-11ea-9c87-1589ea2441cd.jpg)
here is an example.
In the bed sectrion there should be 4 heaters, but only one is shown. Also only one is in the graph.

**Comment by chrishamm** [comment]
You may need RRFv3 to display multiple bed heaters properly but it does work with DWC 2.1.5:

![image](https://user-images.githubusercontent.com/5919449/80482916-6486c200-8955-11ea-97d4-c85747d22152.png)

All configured via
```
M140 P0 H0
M140 P1 H0
M140 P2 H0
```

**Comment by xyyzyyx** [comment]
That's a great news, thanks. 
Seems that there won't be any excuses for upgrading to RRFv3 now :-)
