### ISSUE TITLE
Upload system files button does not upload to the correct sys folder

### ISSUE THREAD

**Issue by natthapolvanasrivilai** [chrishamm/DuetWebControl#243]
When uploading the config.zip from RRF Config Tool. DWC upload the content to the 0:/sys/sys folder instead of just 0:/sys

DWC 2.1.5

![Annotation 2020-04-30 130421](https://user-images.githubusercontent.com/18647332/80677477-261f0d80-8ae3-11ea-9966-c07b05249f3c.png)

**Comment by chrishamm** [comment]
Thanks for reporting this, I'll have a look.

**Comment by chrishamm** [comment]
I could reproduce this problem and will fix it in the upcoming DWC 2.1.6.

**Comment by chrishamm** [comment]
Fixed in DWC 2.1.6.
