### ISSUE TITLE
M905 missing?

### ISSUE THREAD

**Issue by dvmourik** [chrishamm/DuetWebControl#244]
Maybe i missed something... normally DWC sets date and time for logging on the Duet (duet2 in our case). But now it's not automaticly set?

**Comment by chrishamm** [comment]
M905 is only sent from DSF to RRF and not from DWC. DWC uses the rr_connect request to update the datetime.

I'll check this again next week.

**Comment by chrishamm** [comment]
This appears to be working well on my Duet 2 and I can confirm rr_connect is sent with the correct datetime to the Duet. Please make sure you are on the latest Duet Web Control version.
