### ISSUE TITLE
creating a new filament

### ISSUE THREAD

**Issue by cdedwards** [chrishamm/DuetWebControl#249]
I updated to the lastest webcontrol the other day.  Tonight I attempted to create a new filament type and found that there is no option to do so.. There is a "Create File", but no Create Filament.  Create File does exactly that by creating a file in the filament directory instead of creating a directory with load/unload/config g files.

**Comment by cdedwards** [comment]
not sure what happened. I reloaded the webpage, and now its Create Filament.. weird.

**Comment by cdedwards** [comment]
http://prntscr.com/sfox7h

Created my filament, and lo and behold Create File is back.

**Comment by chrishamm** [comment]
What boards and firmware version are you using?

**Comment by cdedwards** [comment]
RepRapFirmware for Duet 2 WiFi/Ethernet 3.01-RC12 (2020-05-06b1)
Duet WiFi Server Version: 1.23
Duet Web Control 2.1.7

**Comment by chrishamm** [comment]
Thanks, this will be fixed in the next version which we are going to release shortly.
