### ISSUE TITLE
Flatten the UI

### ISSUE THREAD

**Issue by iDeveloUK** [chrishamm/DuetWebControl#28]
Would you like me to go through and remove all the shadowing and make the UI flat?

**Comment by chrishamm** [comment]
If you want to make the UI flat, just remove the CSS link which loads bootstrap-theme.css. I for one like DWC better with the shadows and gradients, so I haven't put much thought in this topic yet.

If you like I could make this option variable in DWC 1.16.

**Comment by BrianGilbert** [comment]
I'd like to see a screenshot of the difference, but if it's simple.. +1 on the option

**Comment by iDeveloUK** [comment]
This is with the gradients and border radius removed.
<img width="1428" alt="duetflat" src="https://cloud.githubusercontent.com/assets/20368906/23651300/0cacfdfe-031d-11e7-82d4-f44c82f857f8.png">

**Comment by iDeveloUK** [comment]
And this: 

<img width="1196" alt="flat" src="https://cloud.githubusercontent.com/assets/20368906/23655186/ed6abca6-032b-11e7-8d5b-bade57f608b0.png">

**Comment by iDeveloUK** [comment]
Or something to take part of that boot-strappy feel away
<img width="1412" alt="flat" src="https://cloud.githubusercontent.com/assets/20368906/23675811/7a0455f0-0372-11e7-80b3-abeceed1fda9.png">

**Comment by chrishamm** [comment]
OK, I'll change that behavior in my next version. If you want me to add a new theme (via a new CSS file), send it over and I'll add it.
