### ISSUE TITLE
Replace favicon with print status

### ISSUE THREAD

**Issue by iDeveloUK** [chrishamm/DuetWebControl#31]
This was requested on the duet forums. Using this to replace the favicon with the print status.

[http://lipka.github.io/piecon/](http://lipka.github.io/piecon/)

**Comment by chrishamm** [comment]
Looks like a good idea, I'll keep this in mind for DWC 1.16.

**Comment by iDeveloUK** [comment]
Chris have you started this? If not would you like me to do it and send you a request for review?

**Comment by iDeveloUK** [comment]
Added pull request for this.
