### ISSUE TITLE
Comma in .gcode filename causes error

### ISSUE THREAD

**Issue by MortarArt** [chrishamm/DuetWebControl#35]
![screenshot 60](https://cloud.githubusercontent.com/assets/8252979/25034852/f3f820ee-212c-11e7-8d3f-d4df85127c5b.jpg)

**Issue description:**

.gcode file list parsing does not complete. (See Stars before names in attachment)

**Steps to replicate:**

Upload .gcode file with ' symbol in filename.

**Variations to issue:**

Navigate to System Editor, wait a minute, and return to .gcode list, and all files, except the one with the bad filename are parsed.

Not sure how to delete the file, as the relevant button doesn't appear until parsing is complete.

**Comment by MortarArt** [comment]
Hope I'm in the right place for this.

**Comment by chrishamm** [comment]
Yep, that's the right place. To delete it I suggest you take out the SD card once and delete it using a PC.

I'll change DWC to check filenames for illegal characters before they can be uploaded.
