### ISSUE TITLE
Incorrect Z-Probe type under Machine Properties

### ISSUE THREAD

**Issue by SleepyPrince** [chrishamm/DuetWebControl#36]
Saw this post on the DuetWifi forum.
https://www.duet3d.com/forum/thread.php?id=1342

I looked in to the code and found that the z-probe part in comm.js is not up-to-date.
According to https://duet3d.com/wiki/Connecting_a_Z_probe, there should be Type 1-6.
I am not sure how they should be named so I cannot provide a pull request.

**Comment by chrishamm** [comment]
Thanks, I'll update that enumeration.
