### ISSUE TITLE
Tabbing Between Fields in DWC Causes an Error

### ISSUE THREAD

**Issue by bmalcheski** [chrishamm/DuetWebControl#37]
I am currently running DWC 1.15b but I believe this started on 1.15a. I get the below error when I tab between fields (ie temperature inputs) in the DWC. Currently running FW 1.18.1 and server 1.03(ch fork) I am using Chrome Version 57.0.2987.133

I did not have this issue until I upgraded to 1.15a.

>  JavaScript Error
 A JavaScript error has occurred so the web interface has closed the connection to your board. It is recommended to reload the web interface now. If this happens again, please contact the author and share this error message:
 Message:
Uncaught ReferenceError: windowXsSm is not defined
URL: http://10.0.0.57/js/dwc.js
Line: 74187:38
Error object: {}

**Comment by chrishamm** [comment]
Thanks, I'll fix it in v1.16.
