### ISSUE TITLE
User-Defined Macros Not updated

### ISSUE THREAD

**Issue by Kulitorum** [chrishamm/DuetWebControl#39]
When I first connect to my Duet Wifi, the User-Defined Macros are empty until I visit the Macros page.

Firmware Name:RepRapFirmware for Duet WiFi
Firmware Electronics: Duet WiFi 1.0 + DueX5
Firmware Version: 1.18.1 (2017-04-09)
WiFi Server Version: 1.03 (ch fork)
Web Interface Version: 1.15a

**Comment by JohnOCFII** [comment]
I see the same effect.  It I change pages, it'll populate.

I've seen this primarily with Safari 10.1 on MacOS 10.12.4. on a 2012 MacBook Pro.

**Comment by chrishamm** [comment]
Does this problem persist if you upgrade to v1.15c?

**Comment by Kulitorum** [comment]
Will firmware 1.18.1 work with 1.15c?

**Comment by chrishamm** [comment]
Yes.

**Comment by Kulitorum** [comment]
I just checked, and it is fixed in 1.15c.
