### ISSUE TITLE
Layer time.

### ISSUE THREAD

**Issue by Nickwren** [chrishamm/DuetWebControl#40]
Would it be possible to have the layer time graph keep a track of the times without the web page being open?

**Comment by SleepyPrince** [comment]
Unless the firmware itself saves all the layers time, the web interface won't be able to do anything without being opened.

**Comment by chrishamm** [comment]
It would be possible, but an interface for this functionality is not implemented in the firmware. Without it it's quite impossible to keep track of the layer times unless DWC remains connected.
