### ISSUE TITLE
How to edit?

### ISSUE THREAD

**Issue by Kulitorum** [chrishamm/DuetWebControl#42]
I am building a printer for a customer and I want to make a cut-down version of the web interface. Right now I just want to remove the auto bed compensation section, because the printer needs to use grid calibration and lower the probe first.
If the customer presses auto bed compensation, the printer will headcrash because the probe is not down.

So I downloaded 1.15c and changed reprap.htm (adding style="display: none;") and build it.

But nothing changes.

How can I edit reprap.htm and upload it to the printer easily? - can I access the version that has been copied to the wifi card? - Can I upload only reprap.htm and have it copied to where it needs to be?

Thanks and sorry for being a pain.

**Comment by chrishamm** [comment]
If you are using a Duet WiFi, upgrade to RRF+DWS 1.19 and try that again. Remember you need a UNIX-based OS to build the minified version of the web interface.
