### ISSUE TITLE
JavaScript Error in DWC 1.15b

### ISSUE THREAD

**Issue by PDBeal** [chrishamm/DuetWebControl#46]
So I just ran into this error.  It's not a make or break issue, but is still an issue.  I was setting the temperature for the heater 1 in the Active box to 200.  I press tab (assuming to be able to do this and change from box to box to box), and all of a sudden I'm disconnected with the following error message popup in a red box.

JavaScript Error

A JavaScript error has occurred so the web interface has closed the connection to your board. It is recommended to reload the web interface now. If this happens again, please contact the author and share this error message:

Message: Uncaught ReferenceError: windowXsSm is not defined
URL: http://192.168.2.242/js/dwc.js
Line: 4361:38
Error object: {}

This is on a Duet 0.8.5 running DC42's firmware 1.18.1 (2017-04-09) with Web Interface Version 1.15a

**Comment by chrishamm** [comment]
This is fixed in DWC 1.16.
