### ISSUE TITLE
Webcam as stream not sized

### ISSUE THREAD

**Issue by Alex9779** [chrishamm/DuetWebControl#48]
The new option to embed a webcam as a stream is nice but don't works really.
Not because of the disabled updating, that's fine and I think that was the problem before but because you switch to an iFrame and load the stream in there.
The problem I have is that my webcam image is too huge and I get scroll bars which is annoying.
I had a little look at it and you have limited the size in the css but unfortunately this has no effect on the iFrame. It seems to be a technical limitation, this is not possible AFAIK.
So why not embed the stream just like a normal picture without the iFrame and just disable the updates completely?

**Comment by chrishamm** [comment]
This is already possible - just set the update interval to 0, disable the iframe option and set the webcam source to the JPG URL of your webcam.
