### ISSUE TITLE
Support for embedded VLC

### ISSUE THREAD

**Issue by pcsentinel** [chrishamm/DuetWebControl#59]
Would it be possible to allow  for embedded VLC player, to display webcam output via rtsp, I have got it to work by hacking the page so that the panel_webcam looks like below. it would just need a small change in the interface section to say "use vlc2"
 and allow a rtsp URL in the address input.

<div id="panel_webcam" class="panel panel-default">
									<div class="panel-heading">
										<a id="a_webcam" href="#">Webcam Surveillance</a>
										<span id="span_webcam" class="glyphicon glyphicon-menu-down"></span>
									</div>
									<div class="panel-body">
										<img class="hidden" src="about:blank" id="img_webcam" alt="(image not available)">

										<div id="div_ifm_webcam" class="embed-responsive embed-responsive-16by9"><embed type="application/x-vlc-plugin" pluginspage="http://www.videolan.org" version="VideoLAN.VLCPlugin.2" target="rtsp://User:User12@192.168.xx.xxx:554/videoMain " id="vlc" height="240" width="230">
</div>
									</div>
								</div>

**Comment by chrishamm** [comment]
In principle this is already possible, but you need to create your own HTML file, upload it to the Duet on the Settings page and then include it as an iframe.
