### ISSUE TITLE
Fan control?

### ISSUE THREAD

**Issue by BrianGilbert** [chrishamm/DuetWebControl#6]
Just wondering if there is a a reason there isn't currently any fan controls?

Based on other software I've used it seems like it would make sense to have controls on the "Machine Control" section to control them outright, and in "Print Status" as overridable factors.

**Comment by chrishamm** [comment]
There is, but you must enable it on the Settings page first:

![auswahl_001](https://cloud.githubusercontent.com/assets/5919449/12032338/880acbfe-ae17-11e5-9ba1-790cbbbcbe9a.png)

**Comment by BrianGilbert** [comment]
Thanks Chris
