### ISSUE TITLE
Dark theme is broken in 1.20-RC1

### ISSUE THREAD

**Issue by zlowred** [chrishamm/DuetWebControl#64]
Please see the screenshot attached

![image](https://user-images.githubusercontent.com/134235/33983277-d8ce1c28-e0b3-11e7-8f83-d3780f15cd3d.png)

**Comment by chrishamm** [comment]
I can confirm that and I have fixed it in my local working copy.

**Comment by chrishamm** [comment]
Fixed in RC2.
