### ISSUE TITLE
fan numbers

### ISSUE THREAD

**Issue by lesaux** [chrishamm/DuetWebControl#65]
1st Fan on duet boards is named Fan0, but in web interface it is Fan1. It might be less confusing to use same convention.

**Comment by DanalEstes** [comment]
Agreed.  This substantially slowed my ability to wire and configure a Duet.

**Comment by chrishamm** [comment]
This is already the case when using DWC 1.20.

**Comment by DanalEstes** [comment]
Fantastic!  (Pun Intended).

Thank you for all of your work on this interface.  It is outstanding.
