### ISSUE TITLE
[Feature] Print History

### ISSUE THREAD

**Issue by lesaux** [chrishamm/DuetWebControl#66]
A tab with print history would be nice. Maybe its possible to keep a print history on sdcard?

**Comment by nuker1991** [comment]
Also with statistics like meters/hours printed is nice :)

**Comment by brunofporto** [comment]
Me too....

**Comment by chrishamm** [comment]
This would have to be implemented in the firmware first - the web interface can only display what the firmware provides. Any other solution would be rather dirty. Expanding the rr_fileinfo response could be a solution.

**Comment by JohnOCFII** [comment]
Actually, the most important data to display is already captured when the event log is being created:  Just having a tab to display this data in a nicely formatted way would be great.  Here are two entries that could be used, for example:
`2019-01-31 18:28:16 Started printing file Calibration/3DBenchy_0.2mm_PLA_new_nozzle_RC.gcode
2019-01-31 20:00:28 Finished printing file Calibration/3DBenchy_0.2mm_PLA_new_nozzle_RC.gcode, print time was 1h 32m
`
