### ISSUE TITLE
Show Probed Points problem in Apple Safari

### ISSUE THREAD

**Issue by Am1S** [chrishamm/DuetWebControl#69]
Show probed points not worked in Safari (latest).
![2018-03-04 19 01 34](https://user-images.githubusercontent.com/5885881/36947559-9490893c-1fde-11e8-9700-668b6cb51979.png)

**Comment by chrishamm** [comment]
It seems like ThreeJS is not initialized in your browser but I'm afraid I have no way to fix this because I do not own any Apple products.

**Comment by chrishamm** [comment]
I checked this on OS X and it is all working well. Perhaps try clearing your browser cache and reload the web interface.
