### ISSUE TITLE
Webcam Integration

### ISSUE THREAD

**Issue by nokianhunter** [chrishamm/DuetWebControl#7]
Hi there,

I have a problem with the Webcam URL I enter in DuetWebControl settings.
It needs to point to an image file. So I tried "http://192.168.0.35:8080/photo.jpg", while running the IP Webcam App on Android. (Checked with my browser and it works there.)
But the Print Status Page shows "image not available".
Any hint is appreciated.

Regards
Nokian

**Comment by chrishamm** [comment]
I believe there is a typo in viewmodel.js. Could you open that file, go to line 344 and replace

if (newURL.indexOf("?") != -1) {

with

if (newURL.indexOf("?") == -1) {

and check if that fixes your problem?

**Comment by nokianhunter** [comment]
Well, that did the trick.
Thanks for your fast response!
