### ISSUE TITLE
[request]Flip the embedded webcam?

### ISSUE THREAD

**Issue by gavatron3000** [chrishamm/DuetWebControl#70]
Hello,

As title asks, is it possible to request the options to be able to orientate the webcam stream to your liking? maybe a few tick boxes? 180 and 90 would be perfect :)

kind regards
gav

**Comment by chrishamm** [comment]
This is now supported in DWC 1.21.2-b2.

**Comment by gavatron3000** [comment]
perfect, thanks mate
