### ISSUE TITLE
Web page keeps scrolling back up

### ISSUE THREAD

**Issue by Nickwren** [chrishamm/DuetWebControl#71]
Whenever I scroll down on the webpage it keeps reverting  back to the top.  This happens on Safari and Internet Explorer

**Comment by chrishamm** [comment]
On what pages does this happen? On every page?

**Comment by chrishamm** [comment]
The web interface will no longer scroll up after a file has been edited. I'll change that in my next version. If this seems to happen under other circumstances, please provide better instructions on how this can be reproduced.
