### ISSUE TITLE
Progress bar not working

### ISSUE THREAD

**Issue by Nickwren** [chrishamm/DuetWebControl#76]
When uploading prints the progress bar doesent work.
It has been like this for the last few releases.
On uploading the bar is clear and states “starting” it then sits there and jumps to 100% and green after the files uploaded.
On large files this doesent give you any indication that things are progressing

**Comment by chrishamm** [comment]
What browser were you using when that happened?

**Comment by Nickwren** [comment]
Explorer

**Comment by chrishamm** [comment]
IE is not supported - sorry. Actually you should get a message saying that DWC does not support it when you load it for the first time. Please use a better browser like Chrome or Firefox.
