### ISSUE TITLE
Layer counter will not pass from Layer 2

### ISSUE THREAD

**Issue by CarlosSprekelsen** [chrishamm/DuetWebControl#78]
Layer counter stalls at layer 2, despinte that the layers keep growing. This affects the counter, the layer time and the estimations based on layers. Following screenshot shows Layer 2, while the print is on Layer 23:

![screenshot from 2018-05-12 16-12-23](https://user-images.githubusercontent.com/28190238/39957235-aaeae008-5600-11e8-8d32-a5b5d152fcc6.png)

**Comment by chrishamm** [comment]
This is also a firmware issue and has nothing to do with DWC itself. The firmware passes print information to DWC, which is then displayed on the Print Status page.
