### ISSUE TITLE
rtsp stream

### ISSUE THREAD

**Issue by pkmcnc** [chrishamm/DuetWebControl#8]
Hi,
Is it possible to show rtsp stream from my IP webcam? I can't make it generate a jpg image.
Thanks!

**Comment by chrishamm** [comment]
I don't think most browsers support RTSP, but I could add an option to turn the img tag on the print status page into a video tag. That might work.

**Comment by chrishamm** [comment]
Sorry, RTSP is not supported by common browsers - I don't see a way to add support for it anytime soon.
