### ISSUE TITLE
[Feature request] Touch optimized Template

### ISSUE THREAD

**Issue by JoduWei** [chrishamm/DuetWebControl#83]
I managed to install the webinterface locally to a raspberry pi/pc. Its really easy. It would be really nice to have a touch optimizied version for smaller displays. I mean a full screen condensed interface without scrolling. Maybe a second template file.
I would have to read in everything, since the template is not splitted into modules.

**Comment by chrishamm** [comment]
More customization will be possible in the future but I don't think I will be able to provide that as part of Duet Web Control. It is more likely to expect this as a part of DWC's successor which is still being planned.

**Comment by JoduWei** [comment]
"DWC's successor" ?

**Comment by chrishamm** [comment]
Yes

**Comment by JoduWei** [comment]
Great, tell me, if you need support in form of coding.

**Comment by Patrik-svobodik** [comment]
I think it is safe to close this, the new DWC2 is really well optimized for touch devices

**Comment by chrishamm** [comment]
I will close this when DWC2 is out.

**Comment by chrishamm** [comment]
Please give DWC2 a try, it is better optimized for touch screens.
