### ISSUE TITLE
Negative buttons in M291 dialog have high-end values instead of low-end

### ISSUE THREAD

**Issue by wilriker** [chrishamm/DuetWebControl#87]
https://github.com/chrishamm/DuetWebControl/blob/4deb9baef83227314f6b9c9a5c34f14ea3f37481/core/js/settings.js#L342

The start value of `buttonIndex` for
```
$("#modal_messagebox button.btn-move[data-axis-letter='" + axis + "'][data-amount^='-']")
```
should be 2 or the negative buttons on `M291` dialog will start with the largest value and will only decrease to the third lowest value which might be very coarse.

**Comment by chrishamm** [comment]
Thanks, this has been fixed in v1.22-b2 although the approach is different.
