### ISSUE TITLE
[Feature] email or sms notifications 

### ISSUE THREAD

**Issue by digitalirony** [chrishamm/DuetWebControl#89]
Not sure if this can even be done in js, as these need to connect to servers. But maybe there is some way to do this?

**Comment by Blue-Dust** [comment]
Even if you had to use a seperate server, or even use SNMP, that would be cool.

**Comment by chrishamm** [comment]
I don't want to implement this in DWC - IMO such a notification service should work independently from the GUI. It's better to put this either in RepRapFirmware or on an external controller like a RaspPi.
