### ISSUE TITLE
no picture in Webcam option

### ISSUE THREAD

**Issue by criticallimit** [chrishamm/DuetWebControl#9]
Like the other item with the rtsp stream,
my stream isn´t shown as well. Think it´s a mjpeg stream, but not sure.
This is my url to the cam:

http://192.168.2.27:88/cgi-bin/CGIStream.cgi?cmd=GetMJStream&usr=Webcontrol&pwd=+++++

**Comment by criticallimit** [comment]
If I put the stream direct to the img src it is working. But than the window is not hideable in the webinterface...


<div id="panel_webcam" class="panel panel-default hidden">
									<div class="panel-heading">
										<a id="a_webcam" href="#">Webcam Surveillance</a>
										<span id="span_webcam" class="glyphicon glyphicon-menu-down"></span>
									</div>
									<div class="panel-body">
										<img src="http://192.168.2.27:88/cgi-bin/CGIStream.cgi?cmd=GetMJStream&usr=Webcontrol&pwd=reprap">
								
									</div>
								</div>

**Comment by chrishamm** [comment]
I guess it is the same problem as this one: https://github.com/chrishamm/DuetWebControl/issues/7 Can you check that?

I will fix the described problem in my next DWC version.

**Comment by criticallimit** [comment]
didn´t changed the problem...

**Comment by criticallimit** [comment]
update:

working now. Forgot to clear the browsers cache.

**Comment by chrishamm** [comment]
This has been fixed in v1.09
