### ISSUE TITLE
Implement WSPrint 2.0

### ISSUE THREAD

**Issue by mcumming** [chrishamm/DuetWebControl#92]
Implementing this interface would facilitate RRF based machines interoperating with the new tooling being developed and released by Microsoft in recent Windows 10 releases.

For details see : https://docs.microsoft.com/en-us/windows-hardware/drivers/3dprint/enabling-wsprint-on-a-device

**Comment by Kriechi** [comment]
This is more a feature request for RepRapFirmware.
DuetWebControl (this repository) is only the web frontend for RRF - and only runs in your browser, and as such has no active component running on the Duet board.

Please make a new post to the RRF firmware wishlist (and close this issue): https://forum.duet3d.com/category/8/firmware-wishlist
