### ISSUE TITLE
[DWC2] Unable to get status data

### ISSUE THREAD

**Issue by Patrik-svobodik** [chrishamm/DuetWebControl#95]
Hi, I just compiled DWC2 and it looks stunning, but there is a problem with getting status info, it complains about some timer and some things that disappear quickly, I can home the printer, but it never knows if it is already homed, the same with sending gcode

**Comment by chrishamm** [comment]
What board, printer and browser are you using? If you decide to try it out, it's probably a good idea to run it locally via 'npm run dev'. This makes debugging easier because the stack traces in the JS console are more verbose compared to the on-board variant.

**Comment by Patrik-svobodik** [comment]
I run it locally on my machine with npm run serve, it fails to connect most of the time but when it does id does not receive status from the board
<img width="1552" alt="snimek obrazovky 2018-12-22 v 11 49 54" src="https://user-images.githubusercontent.com/25883885/50374578-73869300-05f0-11e9-961f-c901437d20ff.png">

**Comment by Patrik-svobodik** [comment]
<img width="1552" alt="snimek obrazovky 2018-12-22 v 11 33 40" src="https://user-images.githubusercontent.com/25883885/50374587-987b0600-05f0-11e9-9393-02045b431f5b.png">

**Comment by Patrik-svobodik** [comment]
BTW I think the DWC should detect if you have a probe and if you do then not show the option to do G32 bed leveling

**Comment by Patrik-svobodik** [comment]
I am using a Duet WiFi on RRF 2.02RC6 (the newest)

**Comment by Patrik-svobodik** [comment]
and one other question, I can just build this and put it on the SD card?

**Comment by chrishamm** [comment]
Thanks, will check it out. What browser are you using?

On Saturday, December 22, 2018, Patrik-svobodik <notifications@github.com>
wrote:
> I am using a Duet WiFi on RRF 2.02RC6 (the newest)
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci6.googleusercontent.com/proxy/iz0NxN0sTKLI4YpoULRZWk7bA_a-ylRoyqvbjLYKsEOAwpw5GjeNtdqX1v1lR-yvI14kLiWh82sZMuUDQe8APFLYtraeFHxNxLjSbO6lLVY7lEfLyi9vr8-qdwgFjsFIrxuwRywhWYNW0LiWeFEQybar9A=s0-d-e1-ft#https://github.com/notifications/beacon/AFpS2Qh_nRXQ6T2DIOlDhJLg5Jo1TkHxks5u7i3zgaJpZM4ZfbTx.gif>

**Comment by chrishamm** [comment]
You can build it and upload one of the zip files that are generated in
dist. But I recommend you wait for dc42s next RC first because it improves
support for the new web ui.

On Saturday, December 22, 2018, Christian Hammacher <bmasterc@gmail.com>
wrote:
> Thanks, will check it out. What browser are you using?
>
> On Saturday, December 22, 2018, Patrik-svobodik <notifications@github.com>
wrote:
>> I am using a Duet WiFi on RRF 2.02RC6 (the newest)
>>
>> —
>> You are receiving this because you commented.
>> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci6.googleusercontent.com/proxy/iz0NxN0sTKLI4YpoULRZWk7bA_a-ylRoyqvbjLYKsEOAwpw5GjeNtdqX1v1lR-yvI14kLiWh82sZMuUDQe8APFLYtraeFHxNxLjSbO6lLVY7lEfLyi9vr8-qdwgFjsFIrxuwRywhWYNW0LiWeFEQybar9A=s0-d-e1-ft#https://github.com/notifications/beacon/AFpS2Qh_nRXQ6T2DIOlDhJLg5Jo1TkHxks5u7i3zgaJpZM4ZfbTx.gif>

**Comment by Patrik-svobodik** [comment]
I use safari 12.0.1 (14606.2.104.1.1)

**Comment by Patrik-svobodik** [comment]
just tried deploying it to my duet, it still does not work, although the connecting is almost instant and reliable, but still complains about this:
<img width="1552" alt="snimek obrazovky 2018-12-22 v 15 06 48" src="https://user-images.githubusercontent.com/25883885/50375287-4d1a2500-05fb-11e9-8a1d-720b710364d0.png">

**Comment by Patrik-svobodik** [comment]
the same happens on connect/disconnect

**Comment by Patrik-svobodik** [comment]
and suddenly it cannot connect anymore

**Comment by chrishamm** [comment]
Feel free to try a 'git pull' and test it again, it's working now. Bear in mind that this version is NOT official yet and still in active development.

**Comment by Patrik-svobodik** [comment]
It works now, thanks a lot

**Comment by Patrik-svobodik** [comment]
I see a lot more issues, should I open a new issue?

**Comment by Patrik-svobodik** [comment]
<img width="430" alt="snimek obrazovky 2018-12-22 v 19 50 03" src="https://user-images.githubusercontent.com/25883885/50377742-02ac9e80-0623-11e9-814e-5ec00a7f6131.png">

[Záznam obrazovky 2018-12-22 v 19.42.16.zip](https://github.com/chrishamm/DuetWebControl/files/2705460/Zaznam.obrazovky.2018-12-22.v.19.42.16.zip)

**Comment by Patrik-svobodik** [comment]
for some reason the class="grey lighten-4" is added to the <tr data-v-5e8d53b0=""> element when the tool is selected and starts heating, can you do anything about it?

**Comment by chrishamm** [comment]
As I said the 'next' branch is NOT for production because I am still
working on a lot of details and it is NOT finished yet. Once I release a
first version and you notice problems, feel free to open new issues.

**Comment by Patrik-svobodik** [comment]
I know it is not ready, I am jist pointing out issues

**Comment by chrishamm** [comment]
Sure, thanks. Here my current TODO list:

- file names => inline
- document title => currently selected machine (+ print progress)
- add piecon support again
- utils/merge performance evaluation
- sd card mount: remove error message
- test on-board cache

Let me know if you find anything else!

**Comment by Patrik-svobodik** [comment]
You should invert the default sorting so that it is identical to the old
DWC, or better, make ut so that it remembers what you set, when loading the
GCODEs the whole interface (and sometimes my whole mac) hang and will be
not responding untill it is fully loaded
ne 23. 12. 2018 v 0:42 odesílatel Christian Hammacher <
notifications@github.com> napsal:

**Comment by Patrik-svobodik** [comment]
And add option to not show every gcode that has been run from the UI, it is annoying (as the copyright on the bottom is, but you said it will be moved)

**Comment by Patrik-svobodik** [comment]
and one more thing I find annoying- the button "Start another" is missing

**Comment by Patrik-svobodik** [comment]
BTW is the language picker present as of now? I am working on a Czech translation but I am unable to test it

**Comment by chrishamm** [comment]
Thanks for reporting the issue with the "Start another" - I'll try to reproduce and to fix it.
i18n is prepared but I haven't found more time to prepare the translations for everything but the start page. It's on my TODO list.

**Comment by Patrik-svobodik** [comment]
I am already working on the czech translation, I just duplicated the en.js
file and added it to the index.js, will it change? If yes I will wait and
translate it later
po 24. 12. 2018 v 13:30 odesílatel Christian Hammacher <
notifications@github.com> napsal:

**Comment by Patrik-svobodik** [comment]
another problem, when I send M999 in the console it hangs because it is expecting a response, Merry Christmas BTW

**Comment by Patrik-svobodik** [comment]
another thing - I am unable to upload the doc files

**Comment by Patrik-svobodik** [comment]
dwc files

**Comment by Patrik-svobodik** [comment]
and if I upload the firmware files it does not prompt me to update

**Comment by chrishamm** [comment]
Use the Files/System page

On Tuesday, December 25, 2018, Patrik-svobodik <notifications@github.com>
wrote:
> and if I upload the firmware files it does not prompt me to update
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci3.googleusercontent.com/proxy/Q_jtNw193B1dpMrZLimHy77sB36HmXkrmWtGYW1GUvp5rqjuyz_pzs47kUgxEXfY3XlYgcPABZCPKFZz6Gdl71xXKwF0Yiislvsiqp3WMmt3ZfWgGDpBtOoSfRU1hfdEPHEg1_pHCmFBsv1DiidppIQIfQ=s0-d-e1-ft#https://github.com/notifications/beacon/AFpS2VUrNcq2U2ykDUCT-0os8g6fiDFaks5u8p79gaJpZM4ZfbTx.gif>

**Comment by Patrik-svobodik** [comment]
you broke the print dialog again in RC2

**Comment by chrishamm** [comment]
Works perfectly fine on my setup. What is wrong on yours?

**Comment by Patrik-svobodik** [comment]
Don’t get me wrong, it works, but it should have ‘overflow:’ hidden; set but it does not

**Comment by Patrik-svobodik** [comment]
And one more thing: the G32 bed leveling should be gone if a DWC detects a probe on a cartesian or coreXY machine
