### ISSUE TITLE
branch:next V2: feedback

### ISSUE THREAD

**Issue by Kriechi** [chrishamm/DuetWebControl#97]
Thanks @chrishamm for the amazing looking V2 of DWC! I'm really excited about the new UI!

A bit of feedback from playing around with it for 5min or so:

The copyright-statusbar at the bottom of the page takes up valuable screen space. I would prefer not to see it all the time. On my 13'' laptop, every millimeter of screen space should be used for controls and status information.

It would be nice if the top part, with all the status information, could be collapsed to get more space when editing the config or gcode files at the bottom.

Do you have any plans on extendability / plugins / JS-extensions?
For example, I would like to control my smart plug, which has a REST-API to power on/off my printer, from within DWC. Currently I hacked in a few buttons via a browser extension (Tampermonkey), but it would be really great if I could place those into e.g., `/www/plugins.js` file on my printers SD card, and DWC auto-loads it. 

Any thoughts on that?

**Comment by chrishamm** [comment]
Nice to hear you like it. The copyright bar won't stay in there forever but I left it in for development. I'll move it to the Settings soon.

If you are on a SM layout you get a button in the top right corner allowing you to collapse the global info area if necessary.

There is no support for plugins yet but it is planned. In the meantime you could add your own v-btn (see https://vuetifyjs.com/en/components/buttons) to whatever page/component you want and create a REST call inside (e.g. 'await axios.get('url')' inside an async function). Once done run 'npm run serve' to test it locally and 'npm run build' to generate the final ZIP.
