### ISSUE TITLE
CORS request failed when using non standard port for webserver on Duet

### ISSUE THREAD

**Issue by whosrdaddy** [chrishamm/DuetWebControl#98]
My Duet board is configured at port 21000, when I load the 2.0 GUI (RC2), it tries to connect to http://`my IP`/rr_connect?password=reprap which is obviously wrong because my printer is at  http://`my IP`:21000.
Looking at the code, the fix should be easy,  use location.host (which includes the portnumber) instead of location.hostname.

**Comment by chrishamm** [comment]
Thanks, it should be fixed in RC3.
